spring:
  application:
    name: agent-study
  profiles:
    active: dev
server:
  servlet:
    context-path: /api
  port: 8123

springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.dingwan.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
